import { User } from '../src/types/Employee';

export const _mock_users: User[] = [
  {
    id: 1,
    name: 'Casey Miller',
    email: 'casey.miller@company.com',
    role: 'Developer',
    joinDate: new Date(2023, 7, 8, 9, 16, 39, 374),
    isActive: true,
  },
  {
    id: 2,
    name: 'Avery Rodrigue',
    email: 'avery.rodriguez@company.com',
    role: 'Senior Developer',
    joinDate: new Date(2024, 2, 23, 22, 47, 41, 289),
    isActive: false,
  },
  {
    id: 3,
    name: 'Morgan Miller',
    email: 'morgan.miller@company.com',
    role: 'Director',
    joinDate: new Date(2023, 11, 23, 20, 4, 48, 560),
    isActive: true,
  },
  {
    id: 4,
    name: 'Sage Johnson',
    email: 'sage.johnson@company.com',
    role: 'Developer',
    joinDate: new Date(2023, 5, 9, 12, 25, 33.617),
    isActive: true,
  },
  {
    id: 5,
    name: 'Jamie Brown',
    email: 'jamie.brown@company.com',
    role: 'Director',
    joinDate: new Date(2024, 9, 9, 1, 7, 17, 540),
    isActive: true,
  },
  {
    id: 6,
    name: 'Avery Davis',
    email: 'avery.davis@company.com',
    role: 'Developer',
    joinDate: new Date(2022, 6, 1, 22, 25, 39, 302),
    isActive: true,
  },
  {
    id: 7,
    name: 'Avery Jones',
    email: 'avery.jones@company.com',
    role: 'Analyst',
    joinDate: new Date(2024, 12, 11, 23, 46, 53, 739),
    isActive: true,
  },
  {
    id: 8,
    name: 'Jamie Johnson',
    email: 'jamie.johnson@company.com',
    role: 'Coordinator',
    joinDate: new Date(2022, 2, 4, 21, 25, 58, 190),
    isActive: true,
  },
  {
    id: 9,
    name: 'Avery Williams',
    email: 'avery.williams@company.com',
    role: 'Analyst',
    joinDate: new Date(2024, 4, 26, 18, 23, 56, 727),
    isActive: true,
  },
  {
    id: 10,
    name: 'Quinn Rodrigue',
    email: 'quinn.rodriguez@company.com',
    role: 'Coordinator',
    joinDate: new Date(2024, 10, 14, 5, 23, 9, 763),
    isActive: false,
  },
];
